"""Adicionar desconto de associado

Revision ID: 328851a8ace3
Revises: d076f6af0ed2
Create Date: 2026-09-04 15:07:10.648570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328851a8ace3'
down_revision: Union[str, Sequence[str], None] = 'd076f6af0ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('is_associado', sa.Boolean(), nullable=False))
    op.add_column('vendas', sa.Column('desconto_percentual', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas', 'desconto_percentual')
    op.drop_column('clientes', 'is_associado')
    # ### end Alembic commands ###
